apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ctfd: ctf-pv
    app: ctf-uploads
  name: ctf-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi