apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ctfd: ctf-pv
    app: ctf-logs
  name: ctf-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
