apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.pathType }}
        path: "/"
        backend:
          service:
            name: {{ .Values.app_name }}
            port:
              number: {{ .Values.ports.port }}